### ISSUE TITLE
Location VS

### ISSUE THREAD

**Issue by fdncred** [mazoea/te-builder#1]
Just a tip here. You may want to use [vswhere.exe](https://github.com/Microsoft/vswhere) to locate where visual studio is and then you could automate your batch files.

**Comment by vidiecan** [comment]
@fdncred thank you for the tip. 

The problem on some machines is that the location of msbuild is (sadly) not enough to get our .sln (in fact any .sln) successfully built using the CLI. There were problems with specific paths when older .sln were used with VS 2017. It has been working without any issues with older versions.

**Comment by vidiecan** [comment]
Nevertheless, once the current work flow is not enough, we will use `vswhere` to find the paths.
